<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG75SNWD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG75SNWD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG75SNWD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG75SNWD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG75SNWD\App_KernelDevDebugContainer([
    'container.build_hash' => 'G75SNWD',
    'container.build_id' => 'c89d944b',
    'container.build_time' => 1664925628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG75SNWD');
