<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNPxp9Kn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNPxp9Kn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNPxp9Kn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNPxp9Kn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNPxp9Kn\App_KernelDevDebugContainer([
    'container.build_hash' => 'NPxp9Kn',
    'container.build_id' => '2e2ea8f4',
    'container.build_time' => 1672700390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNPxp9Kn');
