<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYN7sqvw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYN7sqvw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYN7sqvw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYN7sqvw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYN7sqvw\App_KernelDevDebugContainer([
    'container.build_hash' => 'YN7sqvw',
    'container.build_id' => '44143050',
    'container.build_time' => 1669129852,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYN7sqvw');
