<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.725dd7e0.js',
                '/build/9.ef02443a.js',
                '/build/app.959ddb93.js',
            ],
            'css' => [
                '/build/app.f50ca75c.css',
            ],
        ],
    ],
],

]];
