<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.725dd7e0.js',
                '/build/536.bb8404d8.js',
                '/build/app.0079db81.js',
            ],
            'css' => [
                '/build/app.c01a5575.css',
            ],
        ],
    ],
],

]];
